# Generated by Django 4.0.1 on 2022-06-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_room_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='users',
            new_name='user',
        ),
    ]
